import colors from 'vuetify/es5/util/colors'

export default {
  mode: 'universal',
  /*
  ** Headers of the page
  */
  head: {
    titleTemplate: '%s - ' + process.env.npm_package_name,
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: process.env.npm_package_description || '' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
      ,
      {
        rel: 'stylesheet',
        href:
          'https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons'
      }
    ]
  },
  server: {
    host: '0.0.0.0' // default: localhost
  },
  /*
  ** Customize the progress-bar color
  */
  loading: { color: '#fff' },
  /*
  ** Global CSS
  */
  css: [
    '~assets/style/main.css'
  ],
  /*
  ** Plugins to load before mounting the App
  */
  plugins: [
    {src: '~/plugins/vuelidate.js'}
  ],
  /*
  ** Nuxt.js modules
  */
  modules: [
    '@nuxtjs/vuetify',
    '@nuxtjs/axios',
    '@nuxtjs/auth',   /* https://auth.nuxtjs.org/ */
    '@nuxtjs/device'  /* https://github.com/nuxt-community/device-module */
  ],
  /*
  ** Axios module configuration
  ** See https://axios.nuxtjs.org/options
  */
  axios: {
    baseURL: "http://dave.brsg.io:4004/api",
    credentials: true,
    debug: true
  },
  /*
  ** Auth module configuration
  ** See https://auth.nuxtjs.org/
  */
  auth: {
    strategies: {
      local: {
        endpoints: {
          login: { url: '/sessions', method: 'post', propertyName: false },
          logout: { url: '/sessions', method: 'delete' },
          user: { url: '/users/current', method: 'get',  propertyName: false }
        },
        tokenRequired: false,
        tokenType: false
      }
    },
    redirect: {
      login: '/auth',
      logout: '/',
      home: '/desktop'
    }
  },
  /*
  ** vuetify module configuration
  ** https://github.com/nuxt-community/vuetify-module
  **
  ** Palette generated by Material Palette - materialpalette.com/indigo/lime
  ** .dark-primary-color    { background: #303F9F; }
  ** .default-primary-color { background: #3F51B5; }
  ** .light-primary-color   { background: #C5CAE9; }
  ** .text-primary-color    { color: #FFFFFF; }
  ** .accent-color          { background: #CDDC39; }
  ** .primary-text-color    { color: #212121; }
  ** .secondary-text-color  { color: #757575; }
  ** .divider-color         { border-color: #BDBDBD; }
  **
  */
  vuetify: {
    theme: {
      dark: false,
      themes: {
        light: {
          primary: '#74C010',
          secondary: '#74C010',
          accent: '#1B676B',
          background: "#ffffff",  /* '#f9fbe7', */
          info: colors.teal.lighten1,
          warning: colors.amber.base,
          error: colors.deepOrange.accent4,
          success: colors.green.accent3
        }
      },
      options: {
        customProperties: true
      },
    }
  },
  /*
  ** Build configuration
  */
  build: {
    /*
    ** You can extend webpack config here
    */
    extend(config, ctx) {
    }
  },
  env: {
  }
}
